export interface TestMeta {
  id: string;
  title: string;
  subtitle: string;
  description: string;
  emoji: string;
  questionCount: number;
  duration: string;
  category: "personality" | "relationship" | "ability" | "mental_health";
  categoryLabel: string;
  gradient: string;
}

export const testList: TestMeta[] = [
  {
    id: "mbti",
    title: "MBTI 16人格",
    subtitle: "发现你的人格密码",
    description: "探索你是思考者还是感受者，是社交达人还是独处爱好者？28道题揭秘你的16型人格。",
    emoji: "🧠",
    questionCount: 28,
    duration: "5分钟",
    category: "personality",
    categoryLabel: "人格",
    gradient: "bg-gradient-to-br from-purple-500 via-blue-500 to-cyan-400",
  },
  {
    id: "bigfive",
    title: "大五人格测试",
    subtitle: "科学认知你自己",
    description: "探索你的五大性格维度（OCEAN），最科学的自我认知工具",
    emoji: "🌊",
    questionCount: 50,
    duration: "8分钟",
    category: "personality",
    categoryLabel: "人格",
    gradient: "bg-gradient-to-br from-sky-400 via-blue-500 to-indigo-600",
  },
  {
    id: "disc",
    title: "DISC性格测试",
    subtitle: "解码你的行为风格",
    description: "发现你的沟通与行为风格（D/I/S/C），职场人际必备",
    emoji: "🎯",
    questionCount: 24,
    duration: "5分钟",
    category: "personality",
    categoryLabel: "人格",
    gradient: "bg-gradient-to-br from-orange-400 via-red-500 to-pink-500",
  },
  {
    id: "attachment",
    title: "成人依恋模型",
    subtitle: "你的爱情模式是什么？",
    description: "基于ECR-R量表，了解你在亲密关系中的焦虑与回避倾向，发现你的依恋类型。",
    emoji: "💝",
    questionCount: 36,
    duration: "8分钟",
    category: "relationship",
    categoryLabel: "关系",
    gradient: "bg-gradient-to-br from-pink-500 via-rose-400 to-orange-400",
  },
  {
    id: "enneagram",
    title: "九型人格",
    subtitle: "找到你的内在动力",
    description: "九种人格原型，哪一种最像你？了解你的核心驱动力、恐惧和成长方向。",
    emoji: "✨",
    questionCount: 36,
    duration: "7分钟",
    category: "personality",
    categoryLabel: "人格",
    gradient: "bg-gradient-to-br from-amber-400 via-yellow-500 to-lime-400",
  },
  {
    id: "holland",
    title: "霍兰德职业兴趣",
    subtitle: "找到你的职业方向",
    description: "RIASEC六维度测评，发现最适合你的职业类型和发展方向。",
    emoji: "💼",
    questionCount: 30,
    duration: "5分钟",
    category: "ability",
    categoryLabel: "能力",
    gradient: "bg-gradient-to-br from-blue-500 via-indigo-500 to-violet-500",
  },
  {
    id: "lovelang",
    title: "五种爱情语言",
    subtitle: "你的爱情表达方式",
    description: "你的爱情表达方式是什么？帮助情侣深度沟通",
    emoji: "💕",
    questionCount: 30,
    duration: "6分钟",
    category: "relationship",
    categoryLabel: "关系",
    gradient: "bg-gradient-to-br from-rose-400 via-pink-400 to-fuchsia-500",
  },
  {
    id: "iq",
    title: "智商IQ测试",
    subtitle: "挑战你的脑力",
    description: "快速测测你的智力水平（简易版瑞文矩阵）",
    emoji: "🧩",
    questionCount: 20,
    duration: "10分钟",
    category: "ability",
    categoryLabel: "能力",
    gradient: "bg-gradient-to-br from-emerald-400 via-cyan-500 to-blue-500",
  },
  {
    id: "adhd",
    title: "成人ADHD筛查",
    subtitle: "注意力自测",
    description: "基于ASRS v1.1量表，18道题初步筛查成人注意力缺陷/多动特征。",
    emoji: "⚡",
    questionCount: 18,
    duration: "3分钟",
    category: "mental_health",
    categoryLabel: "心理健康",
    gradient: "bg-gradient-to-br from-red-400 via-orange-400 to-yellow-400",
  },
  {
    id: "eq",
    title: "情商EQ测试",
    subtitle: "你的情商有多高？",
    description: "33道题全面评估你的情商水平，涵盖自我认知、社交认知等5大维度。",
    emoji: "💡",
    questionCount: 33,
    duration: "6分钟",
    category: "ability",
    categoryLabel: "能力",
    gradient: "bg-gradient-to-br from-emerald-400 via-teal-500 to-cyan-500",
  },
  {
    id: "mbti64",
    title: "MBTI 64型人格",
    subtitle: "16型升级版！",
    description: "新增果断/纠结+温暖/高冷维度，更精准揭秘隐藏性格",
    emoji: "🧬",
    questionCount: 40,
    duration: "8分钟",
    category: "personality",
    categoryLabel: "人格",
    gradient: "bg-gradient-to-br from-fuchsia-500 via-purple-600 to-blue-600",
  },
  {
    id: "hsp",
    title: "高敏感人格(HSP)",
    subtitle: "你容易被环境「电到」吗？",
    description: "测测敏感度，学会保护自己",
    emoji: "🦋",
    questionCount: 25,
    duration: "5分钟",
    category: "mental_health",
    categoryLabel: "心理健康",
    gradient: "bg-gradient-to-br from-violet-400 via-purple-400 to-fuchsia-400",
  },
  {
    id: "pleaser",
    title: "讨好型人格测试",
    subtitle: "总把别人需求放第一？",
    description: "发现讨好模式，学会说不",
    emoji: "🥺",
    questionCount: 28,
    duration: "6分钟",
    category: "personality",
    categoryLabel: "人格",
    gradient: "bg-gradient-to-br from-rose-400 via-pink-500 to-red-500",
  },
  {
    id: "mentalburn",
    title: "精神内耗测试",
    subtitle: "大脑24小时在线？",
    description: "测测内耗程度，学着放过自己",
    emoji: "🔥",
    questionCount: 20,
    duration: "4分钟",
    category: "mental_health",
    categoryLabel: "心理健康",
    gradient: "bg-gradient-to-br from-orange-500 via-red-500 to-rose-600",
  },
  {
    id: "boundary",
    title: "边界感测试",
    subtitle: "铁墙还是棉花糖？",
    description: "保护能量，关系更健康",
    emoji: "🏰",
    questionCount: 22,
    duration: "5分钟",
    category: "ability",
    categoryLabel: "能力",
    gradient: "bg-gradient-to-br from-teal-400 via-emerald-500 to-green-600",
  },
  {
    id: "talent2026",
    title: "2026天赋测试",
    subtitle: "第一眼看到什么？",
    description: "看图决定你2026最闪耀天赋",
    emoji: "👁️",
    questionCount: 3,
    duration: "30秒",
    category: "personality",
    categoryLabel: "人格",
    gradient: "bg-gradient-to-br from-yellow-400 via-amber-500 to-orange-500",
  },
];

export const categories = [
  { key: "all", label: "全部" },
  { key: "personality", label: "🧠 人格" },
  { key: "relationship", label: "💕 关系" },
  { key: "ability", label: "⚡ 能力" },
  { key: "mental_health", label: "🩺 心理健康" },
];
